channels:
- conda-forge
dependencies:
- python=3.11.11
- pip<=24.2
- pip:
  - mlflow==2.20.2
  - cloudpickle==3.1.1
  - numpy==1.23.5
  - psutil==6.1.0
  - scikit-learn==1.4.0
  - scipy==1.10.0
name: mlflow-env
